spring.application.name=SpringBootDemo2

#paymentGateway.type=paytm
#paymentGateway.retryCount=15

payment-property.type=paytm
payment-property.retry-count=5
payment-property.is-enabled=true
payment-property.timeout=3000