spring.application.name=StudentManagementSystem

# MySQL Connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=dbtester
spring.datasource.password=dbtester@123

# Following tells allows jpa to tell hibernate that internally you can create tables on you own, based on entity class
spring.jpa.hibernate.ddl-auto=update

# following will show the query ran at background in the terminal
# default value is false
spring.jpa.show-sql=true

# following allows to properly display the SQL Query ran by hibernate in terminal
spring.jpa.properties.hibernate.format-sql=true